
###
POST http://localhost:8000/api/register
Content-Type: application/json

{

  "full_name": "admin one ",
  "email": "admin1@gmail.com",
  "contact_phone": "0722227154",
  "address": "10 kenya",
  "role": "admin",
  "password": "admin1"
}
###
###
POST http://localhost:8000/api/register
Content-Type: application/json

{

  "full_name": "therapist one ",
  "email": "therapist1@gmail.com",
  "contact_phone": "0712345678",
  "address": "34 kenya",
  "role": "therapist",
  "password": "therapist1"
}
###
###
POST http://localhost:8000/api/register
Content-Type: application/json

{

   "full_name": "user one",
   "email": "user1@gmail.com",
   "contact_phone": "0712345678",
   "address": "123 Kenya",
   "role": "user",
  "password": "user1"
}
###
POST    http://localhost:8000/api/login
Content-Type: application/json
 
  {  
    "email": "admin1@gmail.com",
    "password": "admin1"
  }

###
POST    http://localhost:8000/api/login
Content-Type: application/json
 
  {  
    "email": "therapist1@gmail.com",
    "password": "therapist1"
  }
###
POST http://localhost:8000/api/login
Content-Type: application/json
 
  {  
    "email": "user1@gmail.com",
    "password": "user1"
  }

