
###
POST http://localhost:8000/api/register
Content-Type: application/json

{

  "full_name": "cyrus admin2",
  "email": "cyrusadmin2@gmail.com",
  "contact_phone": "0722227054",
  "address": "10 kenya",
  "role": "admin",
  "password": "cyrus1234"
}
###
###
POST http://localhost:8000/api/register
Content-Type: application/json

{

  "full_name": "therapist one ",
  "email": "therapist1@gmail.com",
  "contact_phone": "0712345678",
  "address": "34 kenya",
  "role": "therapist",
  "password": "therapist1"
}
###
###
POST http://localhost:8000/api/register
Content-Type: application/json

{

   "full_name": "cyrus admin",
   "email": "cyrusadmin@gmail.com",
   "contact_phone": "0712345678",
   "address": "123 Kenya",
   "role": "usadminer",
  "password": "cyrus1234"
}
###
POST    http://localhost:8000/api/login
Content-Type: application/json
 
  {  
    "email": "cyrusadmin@gmail.com",
    "password": "cyrus1234"
  }

###
POST    http://localhost:8000/api/login
Content-Type: application/json
 
  {  
    "email": "therapist1@gmail.com",
    "password": "therapist1"
  }
###
POST http://localhost:8000/api/login
Content-Type: application/json
 
  {  
    "email": "user1@gmail.com",
    "password": "user1"
  }

